SELECT
    (SALARY * MONTHS),
    COUNT(SALARY)
FROM
    EMPLOYEE
WHERE
    (SALARY * MONTHS) IN (
        SELECT
            MAX(SALARY * MONTHS)
        FROM
            EMPLOYEE
    )
GROUP BY
    (SALARY * MONTHS);