SELECT
    S.HACKER_ID,
    H.NAME
FROM
    HACKERS H
    JOIN SUBMISSIONS S ON S.HACKER_ID = H.HACKER_ID
    JOIN CHALLENGES C ON C.CHALLENGE_ID = S.CHALLENGE_ID
    JOIN DIFFICULTY D ON C.DIFFICULTY_LEVEL = D.DIFFICULTY_LEVEL
WHERE
    D.DIFFICULTY_LEVEL = C.DIFFICULTY_LEVEL
    AND D.SCORE = S.SCORE
GROUP BY
    S.HACKER_ID,
    H.NAME
HAVING
    COUNT(S.HACKER_ID) > 1
ORDER BY
    COUNT(S.HACKER_ID) DESC,
    HACKER_ID ASC;